name: Generate Pacman

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Hemanthkumar25s
          output_dir: dist
