name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Hemanthkumar25s
