name: Generate Pacman

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Hemanthkumar25s
          commit_message: "Generate Pacman"
